services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    container_name: rocket_php_container
    volumes:
      - ./src:/var/www/laravel
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    user: ${MY_UID}:${MY_GID}
    environment:
      - QUEUE_CONNECTION=redis
      - MY_UID=${MY_UID}
      - MY_GID=${MY_GID}
    networks:
      - default

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - env/mysql.env
    volumes:
      - ./mysql/data:/var/lib/mysql

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.100.0/24"
